version: '3.2'

services:
  react-validated:
    image: react-validated
    container_name: react-validated
    build:
      context: ./
      dockerfile: dockerfile
    volumes:
      - .:/root/react-validated
      - type: volume
        source: node_modules
        target: /root/react-validated/node_modules
        volume:
          nocopy: true
    ports:
      - "3000:3000"
    networks: 
      - net

networks: 
  net:
    driver: bridge

volumes:
  node_modules: